// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1faYpeQGl9XaIIsl2y_it4RcU_4UtzXA',
    appId: '1:384915080709:android:d5856fd2caa25c247b3e6c',
    messagingSenderId: '384915080709',
    projectId: 'palmvibe-59ae2',
    databaseURL: 'https://palmvibe-59ae2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'palmvibe-59ae2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1fwWZ2Vdp47-pwbRLF1HMBvqsv-eW2tA',
    appId: '1:384915080709:ios:be5216ffc597c95c7b3e6c',
    messagingSenderId: '384915080709',
    projectId: 'palmvibe-59ae2',
    databaseURL: 'https://palmvibe-59ae2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'palmvibe-59ae2.firebasestorage.app',
    androidClientId: '384915080709-6739tu5i4lmfe45ue4rto72lovsqga9v.apps.googleusercontent.com',
    iosClientId: '384915080709-i7cfop74ipg56lrpi92o64ne0u7bp6n3.apps.googleusercontent.com',
    iosBundleId: 'com.ham-tech.palmvibeios',
  );
}
